import 'dart:convert';
import 'dart:io';

import 'package:era_connect/src/cbor/decode.dart';
import 'package:era_connect/src/cbor/model.dart';
import 'package:era_connect/src/chains/bch.dart';
import 'package:era_connect/src/chains/shared.dart';
import 'package:era_connect/src/core/bytes.dart';
import 'package:era_connect/src/core/errors.dart';
import 'package:era_connect/src/tron_proto/gzip.dart';
import 'package:era_connect/src/verify/bch.dart';
import 'package:era_connect/src/verify/result.dart';
import 'package:test/test.dart';

/// Parity against the TypeScript SDK: fixtures in
/// `test/fixtures/parity/bch.json` are generated by the reference
/// implementation from fixed synthetic inputs; the Dart port must produce the
/// identical request bytes and read the identical replies. The envelope
/// embeds gzip (not byte-portable across encoders), so requests pin the
/// POST-GUNZIP protobuf (`protoHex`) plus the CBOR map's origin string
/// instead of the raw cbor.
void main() {
  final fixture = jsonDecode(
    File('test/fixtures/parity/bch.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final requests = (fixture['requests'] as List).cast<Map<String, dynamic>>();
  final replies = (fixture['replies'] as List).cast<Map<String, dynamic>>();

  List<BchTxInput> inputsOf(Map<String, dynamic> props) => [
        for (final raw
            in (props['inputs'] as List).cast<Map<String, dynamic>>())
          BchTxInput(
            txid: raw['txid'] as String,
            index: raw['index'] as int,
            value: raw['value'] as int,
            publicKey: raw['publicKeyHex'] as String,
            path: raw['path'] as String,
          ),
      ];

  List<BchTxOutput> outputsOf(Map<String, dynamic> props) => [
        for (final raw
            in (props['outputs'] as List).cast<Map<String, dynamic>>())
          BchTxOutput(
            address: raw['address'] as String,
            value: raw['value'] as int,
            isChange: raw['isChange'] as bool?,
            changeAddressPath: raw['changeAddressPath'] as String?,
          ),
      ];

  SignRequest<BchSignatureResult> rebuild(Map<String, dynamic> entry) {
    final props = entry['props'] as Map<String, dynamic>;
    return BchChain().generateSignRequest(BchSignRequestProps(
      requestId: props['requestId'] as String,
      inputs: inputsOf(props),
      outputs: outputsOf(props),
      fee: props['fee'] as int,
      dustThreshold: props['dustThreshold'] as int?,
      memo: props['memo'] as String?,
      xfp: props['xfp'] as int,
      timestamp: props['timestamp'] as int?,
      origin: props['origin'] as String?,
    ));
  }

  group('BCH parity: requests', () {
    for (final entry in requests) {
      test('${entry['name']} rebuilds byte-identical', () {
        final request = rebuild(entry);
        expect(request.ur.type, entry['urType']);
        final map = cborDecode(request.ur.cbor);
        expect(asText(mapGet(map, 2)), entry['origin']);
        final proto = gunzipCapped(asBytes(mapGet(map, 1))!, 64 * 1024);
        expect(bytesToHex(proto), entry['protoHex']);
      });
    }
  });

  group('BCH parity: replies', () {
    final byName = {for (final r in requests) r['name'] as String: r};

    BchSignatureResult parseVia(Map<String, dynamic> reply) {
      final request = rebuild(byName[reply['requestName'] as String]!);
      final scanner = request.scanner();
      scanner.receivePart(reply['ur'] as String);
      return scanner.parse();
    }

    VerifyResult runVerify(Map<String, dynamic> reply) {
      final parsed = reply['parsed'] as Map<String, dynamic>;
      final args = reply['verify'] as Map<String, dynamic>;
      return verifyBchSignedTx(VerifyBchSignedTxArgs(
        rawTx: parsed['rawTxHex'] as String,
        inputs: [
          for (final raw
              in (args['inputs'] as List).cast<Map<String, dynamic>>())
            VerifyBchInput(
              txid: raw['txid'] as String,
              index: raw['index'] as int,
              value: raw['value'] as int,
              publicKey: raw['publicKeyHex'] as String,
            ),
        ],
        outputs: [
          for (final raw
              in (args['outputs'] as List).cast<Map<String, dynamic>>())
            VerifyBchOutput(
              address: raw['address'] as String,
              value: raw['value'] as int,
            ),
        ],
        txId: args['txId'] as String?,
      ));
    }

    for (final reply in replies) {
      final expected = reply['expect'] as String;
      test('${reply['name']} -> $expected', () {
        if (expected.startsWith('throws:')) {
          final code = expected.substring('throws:'.length);
          final request = rebuild(byName[reply['requestName'] as String]!);
          final scanner = request.scanner();
          scanner.receivePart(reply['ur'] as String);
          expect(
            scanner.parse,
            throwsA(isA<EraSdkError>().having((e) => e.code, 'code', code)),
          );
          return;
        }

        final parsedExpectation = reply['parsed'] as Map<String, dynamic>;
        final parsed = parseVia(reply);
        expect(bytesToHex(parsed.requestId), parsedExpectation['requestIdHex']);
        expect(parsed.txId, parsedExpectation['txId']);
        expect(parsed.rawTx, parsedExpectation['rawTxHex']);

        final verdict = runVerify(reply);
        switch (expected) {
          case 'verify:true':
            expect(verdict.ok, isTrue);
            expect(verdict.checked, isTrue);
          case 'verify:false':
            expect(verdict.ok, isFalse);
          default:
            throw StateError('unknown expectation $expected');
        }
      });
    }

    test('standalone parseSignature validates the echo too', () {
      final signed = replies.firstWhere((r) => r['name'] == 'signedReply');
      final chain = BchChain();
      final parsed = chain.parseSignature(
        signed['ur'] as String,
        const ExpectedReply(requestId: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
      );
      final parsedExpectation = signed['parsed'] as Map<String, dynamic>;
      expect(parsed.rawTx, parsedExpectation['rawTxHex']);

      final tampered =
          replies.firstWhere((r) => r['name'] == 'wrongRequestIdEcho');
      expect(
        () => chain.parseSignature(
          tampered['ur'] as String,
          const ExpectedReply(
              requestId: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
        ),
        throwsA(isA<EraSdkError>()
            .having((e) => e.code, 'code', 'request-id-mismatch')),
      );
    });
  });
}
