import 'dart:convert';
import 'dart:io';

import 'package:era_connect/src/chains/btc.dart';
import 'package:era_connect/src/chains/shared.dart';
import 'package:era_connect/src/core/bytes.dart';
import 'package:era_connect/src/core/errors.dart';
import 'package:era_connect/src/verify/btc.dart';
import 'package:test/test.dart';

/// Parity against the reference vectors: fixtures generated by running the
/// reference implementation on fixed synthetic inputs (the standard public
/// test seed). For identical inputs this port must produce BYTE-IDENTICAL
/// request CBOR, parse the same replies to the same fields, and return the
/// same verification verdicts.
void main() {
  final fixture =
      jsonDecode(File('test/fixtures/parity/btc.json').readAsStringSync())
          as Map<String, dynamic>;
  final btc = BtcChain(EraConnectConfig(origin: fixture['origin'] as String));
  final requestId = fixture['requestId'] as String;

  group('requests rebuild byte-for-byte', () {
    final requests =
        (fixture['requests'] as List<dynamic>).cast<Map<String, dynamic>>();

    for (final request in requests) {
      test(request['name'] as String, () {
        final props = request['props'] as Map<String, dynamic>;
        final built = request['name'] == 'message'
            ? btc.generateMessageSignRequest(BtcMessageSignRequestProps(
                requestId: props['requestId'] as String,
                message: hexToBytes(props['messageHex'] as String),
                path: props['path'] as String,
                xfp: props['xfp'] as String,
                address: props['address'] as String,
              ))
            : btc.generatePsbtSignRequest(BtcPsbtSignRequestProps(
                psbt: hexToBytes(props['psbtHex'] as String),
                coin: PsbtCoin.values.byName(props['coin'] as String),
              ));
        expect(built.ur.type, request['urType']);
        expect(bytesToHex(built.ur.cbor), request['cborHex']);
      });
    }
  });

  group('replies parse to the recorded fields', () {
    final replies =
        (fixture['replies'] as List<dynamic>).cast<Map<String, dynamic>>();

    for (final reply in replies) {
      final name = reply['name'] as String;
      final ur = reply['ur'] as String;
      final isMessage = name.startsWith('message');

      Object parse() => isMessage
          ? btc.parseMessageSignature(ur, ExpectedReply(requestId: requestId))
          : btc.parsePsbt(ur);

      final expectation = reply['expect'] as String?;
      if (expectation != null) {
        final code = expectation.substring('throws:'.length);
        test('$name refuses with $code', () {
          expect(parse,
              throwsA(isA<EraSdkError>().having((e) => e.code, 'code', code)));
        });
        continue;
      }

      final parsed = reply['parsed'] as Map<String, dynamic>;
      test(name, () {
        if (isMessage) {
          final result = parse() as BtcMessageSignatureResult;
          expect(bytesToHex(result.requestId), parsed['requestIdHex']);
          expect(bytesToHex(result.signature), parsed['signatureHex']);
          expect(result.signatureBase64, parsed['signatureBase64']);
          expect(bytesToHex(result.publicKey!), parsed['publicKeyHex']);
        } else {
          final result = parse() as BtcPsbtResult;
          expect(bytesToHex(result.psbt), parsed['psbtHex']);
        }
      });
    }
  });

  group('verification verdicts match', () {
    final checks =
        (fixture['verify'] as List<dynamic>).cast<Map<String, dynamic>>();

    for (final check in checks) {
      test(check['name'] as String, () {
        final result = check['kind'] == 'message-header'
            ? verifyBtcMessageHeader(VerifyBtcMessageHeaderArgs(
                address: check['address'] as String,
                signature: hexToBytes(check['signatureHex'] as String),
              ))
            : verifySignedPsbt(VerifySignedPsbtArgs(
                sentPsbt: hexToBytes(check['sentPsbtHex'] as String),
                signedPsbt: hexToBytes(check['signedPsbtHex'] as String),
              ));
        if (check['expect'] == 'verify:true') {
          expect(result.ok, isTrue);
          expect(result.checked, isTrue);
        } else {
          expect(result.ok, isFalse);
        }
      });
    }
  });
}
