import 'dart:convert';
import 'dart:io';

import 'package:era_connect/src/chains/cardano.dart';
import 'package:era_connect/src/chains/shared.dart';
import 'package:era_connect/src/core/bytes.dart';
import 'package:era_connect/src/core/errors.dart';
import 'package:era_connect/src/crypto/digests.dart';
import 'package:era_connect/src/verify/cardano.dart';
import 'package:test/test.dart';

/// Parity against the reference vectors: the fixture is generated by the reference
/// implementation from fixed inputs; the Dart port must rebuild every request
/// byte-identically and agree on every reply parse and verdict.
void main() {
  final fixture = (jsonDecode(
    File('test/fixtures/parity/cardano.json').readAsStringSync(),
  ) as Map)
      .cast<String, Object?>();

  final origin = fixture['origin']! as String;
  final requestId = fixture['requestId']! as String;
  final signData = hexToBytes(fixture['signDataHex']! as String);
  final key = (fixture['key']! as Map).cast<String, Object?>();
  final account = VerifyCardanoAccount(
    publicKey: hexToBytes(key['accountPublicKeyHex']! as String),
    chainCode: hexToBytes(key['accountChainCodeHex']! as String),
    accountPath: fixture['accountPath']! as String,
  );
  final chain = CardanoChain(EraConnectConfig(origin: origin));

  List<CardanoUtxoRef> utxosFrom(List<Object?> raw) {
    return raw.map((entry) {
      final m = (entry! as Map).cast<String, Object?>();
      return CardanoUtxoRef(
        transactionHash: hexToBytes(m['transactionHashHex']! as String),
        index: m['index']! as int,
        path: m['path']! as String,
        xfp: m['xfp']!,
        amount: m['amount'] as String?,
        address: m['address'] as String?,
      );
    }).toList();
  }

  List<CardanoCertKeyRef>? certKeysFrom(List<Object?>? raw) {
    if (raw == null) return null;
    return raw.map((entry) {
      final m = (entry! as Map).cast<String, Object?>();
      final keyHashHex = m['keyHashHex'] as String?;
      return CardanoCertKeyRef(
        path: m['path']! as String,
        xfp: m['xfp']!,
        keyHash: keyHashHex == null ? null : hexToBytes(keyHashHex),
      );
    }).toList();
  }

  test('the tx-body digest matches the reference computation', () {
    expect(
      bytesToHex(blake2b256(firstArrayItemBytes(signData))),
      fixture['txBodyDigestHex'],
    );
  });

  group('requests rebuild byte-identically', () {
    for (final entry in fixture['requests']! as List<Object?>) {
      final item = (entry! as Map).cast<String, Object?>();
      final name = item['name']! as String;
      test(name, () {
        final props = (item['props']! as Map).cast<String, Object?>();
        final request = chain.generateSignRequest(CardanoSignRequestProps(
          requestId: requestId,
          signData: signData,
          utxos: utxosFrom(props['utxos']! as List<Object?>),
          certKeys: certKeysFrom(props['certKeys'] as List<Object?>?),
        ));
        expect(request.ur.type, item['urType']);
        expect(bytesToHex(request.ur.cbor), item['cborHex']);
        expect(request.ur.toString(), item['ur']);
      });
    }
  });

  group('replies parse and verify to the recorded verdicts', () {
    for (final entry in fixture['replies']! as List<Object?>) {
      final item = (entry! as Map).cast<String, Object?>();
      final name = item['name']! as String;
      test(name, () {
        final parsed = chain.parseSignature(
          item['ur']! as String,
          ExpectedReply(requestId: requestId),
        );
        final expected = (item['parsed']! as Map).cast<String, Object?>();
        expect(bytesToHex(parsed.requestId), expected['requestIdHex']);
        expect(bytesToHex(parsed.witnessSet), expected['witnessSetHex']);
        final expectedWitnesses = (expected['witnesses']! as List<Object?>)
            .map((w) => (w! as Map).cast<String, Object?>())
            .toList();
        expect(parsed.witnesses.length, expectedWitnesses.length);
        for (var i = 0; i < expectedWitnesses.length; i++) {
          expect(bytesToHex(parsed.witnesses[i].vkey),
              expectedWitnesses[i]['vkeyHex']);
          expect(bytesToHex(parsed.witnesses[i].signature),
              expectedWitnesses[i]['signatureHex']);
        }
        final verify = (item['verify']! as Map).cast<String, Object?>();
        final result = verifyCardanoSignature(VerifyCardanoSignatureArgs(
          signData: signData,
          witnessSet: parsed.witnessSet,
          account: account,
          signerPaths: (verify['signerPaths']! as List<Object?>).cast<String>(),
        ));
        expect(item['verdict'], 'verify:true');
        expect(result.ok, isTrue, reason: result.reason);
        expect(result.checked, isTrue);
      });
    }
  });

  group('tampered replies fail the recorded way', () {
    for (final entry in fixture['tampered']! as List<Object?>) {
      final item = (entry! as Map).cast<String, Object?>();
      final name = item['name']! as String;
      final expectation = item['expect']! as String;
      test(name, () {
        if (expectation.startsWith('throws:')) {
          final code = expectation.substring('throws:'.length);
          expect(
            () => chain.parseSignature(
              item['ur']! as String,
              ExpectedReply(requestId: requestId),
            ),
            throwsA(isA<EraSdkError>().having((e) => e.code, 'code', code)),
          );
          return;
        }
        expect(expectation, 'verify:false');
        final parsed = chain.parseSignature(
          item['ur']! as String,
          ExpectedReply(requestId: requestId),
        );
        final expected = (item['parsed']! as Map).cast<String, Object?>();
        expect(bytesToHex(parsed.requestId), expected['requestIdHex']);
        expect(bytesToHex(parsed.witnessSet), expected['witnessSetHex']);
        final verify = (item['verify']! as Map).cast<String, Object?>();
        final result = verifyCardanoSignature(VerifyCardanoSignatureArgs(
          signData: signData,
          witnessSet: parsed.witnessSet,
          account: account,
          signerPaths: (verify['signerPaths']! as List<Object?>).cast<String>(),
        ));
        expect(result.ok, isFalse);
      });
    }
  });
}
