import 'dart:convert';
import 'dart:io';

import 'package:era_connect/src/chains/cosmos.dart';
import 'package:era_connect/src/chains/shared.dart';
import 'package:era_connect/src/core/bytes.dart';
import 'package:era_connect/src/core/errors.dart';
import 'package:era_connect/src/verify/cosmos.dart';
import 'package:era_connect/src/verify/result.dart' show VerifyResult;
import 'package:test/test.dart';

/// Parity against the TypeScript SDK: fixtures generated by running the TS
/// implementation over fixed synthetic inputs (the standard test seed,
/// requestId 9b1deb4d-…). Requests must re-encode byte-for-byte; replies must
/// parse to the recorded fields; verdicts (including the tampered ones) must
/// match.
void main() {
  final fixture =
      jsonDecode(File('test/fixtures/parity/cosmos.json').readAsStringSync())
          as Map<String, dynamic>;
  final requests = fixture['requests'] as List;

  SignRequest<CosmosSignatureResult> build(Map<String, dynamic> req) {
    final props = req['props'] as Map<String, dynamic>;
    final chain = CosmosChain();
    final signData = hexToBytes(props['signDataHex'] as String);
    if (req['method'] == 'generateSignRequest') {
      return chain.generateSignRequest(CosmosSignRequestProps(
        requestId: props['requestId'] as String,
        signData: signData,
        dataType: props['dataType'] as int,
        path: props['path'] as String,
        xfp: props['xfp'] as Object,
        address: props['address'] as String?,
        origin: props['origin'] as String?,
      ));
    }
    return chain.generateEthermintSignRequest(EthermintSignRequestProps(
      requestId: props['requestId'] as String,
      signData: signData,
      dataType: props['dataType'] as int,
      path: props['path'] as String,
      xfp: props['xfp'] as Object,
      address: props['address'] as String?,
      origin: props['origin'] as String?,
    ));
  }

  VerifyResult runVerify(Map<String, dynamic> spec) {
    final expected = spec['expectedPublicKeyHex'] as String?;
    return verifyCosmosSignature(VerifyCosmosSignatureArgs(
      signData: hexToBytes(spec['signDataHex'] as String),
      digest: spec['digest'] == 'keccak256'
          ? CosmosDigest.keccak256
          : CosmosDigest.sha256,
      signature: hexToBytes(spec['signatureHex'] as String),
      publicKey: hexToBytes(spec['publicKeyHex'] as String),
      expectedPublicKey: expected == null ? null : hexToBytes(expected),
    ));
  }

  group('cosmos parity', () {
    test('requests re-encode byte-for-byte', () {
      for (final r in requests) {
        final req = r as Map<String, dynamic>;
        final built = build(req);
        expect(built.ur.type, req['urType']);
        expect(bytesToHex(built.ur.cbor), req['cborHex'],
            reason: '${req['method']} ${req['props']}');
      }
    });

    test('replies parse to the recorded fields and verify', () {
      for (final r in fixture['replies'] as List) {
        final reply = r as Map<String, dynamic>;
        final request = build(
            requests[reply['requestIndex'] as int] as Map<String, dynamic>);
        final scanner = request.scanner();
        scanner.receivePart(reply['ur'] as String);
        final parsed = scanner.parse();
        final expected = reply['parsed'] as Map<String, dynamic>;
        expect(bytesToHex(parsed.requestId), expected['requestIdHex']);
        expect(bytesToHex(parsed.signature), expected['signatureHex']);
        final pubHex = expected['publicKeyHex'] as String?;
        if (pubHex == null) {
          expect(parsed.publicKey, isNull);
        } else {
          expect(bytesToHex(parsed.publicKey!), pubHex);
        }
        final verdict = runVerify(reply['verify'] as Map<String, dynamic>);
        expect(verdict.ok, reply['verdict'] == 'verify:true',
            reason: reply['name'] as String);
      }
    });

    test('tampered variants fail the recorded way', () {
      for (final t in fixture['tampered'] as List) {
        final tampered = t as Map<String, dynamic>;
        final spec = tampered['expect'] as String;
        if (spec.startsWith('throws:')) {
          final code = spec.substring('throws:'.length);
          final request = build(requests[tampered['requestIndex'] as int]
              as Map<String, dynamic>);
          final scanner = request.scanner();
          scanner.receivePart(tampered['ur'] as String);
          expect(
            scanner.parse,
            throwsA(isA<EraSdkError>().having((e) => e.code, 'code', code)),
            reason: tampered['name'] as String,
          );
        } else {
          expect(spec, 'verify:false');
          final verdict = runVerify(tampered['verify'] as Map<String, dynamic>);
          expect(verdict.ok, isFalse, reason: tampered['name'] as String);
        }
      }
    });
  });
}
