import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:era_connect/src/chains/evm.dart';
import 'package:era_connect/src/chains/shared.dart';
import 'package:era_connect/src/core/bytes.dart';
import 'package:era_connect/src/core/errors.dart';
import 'package:era_connect/src/scan/ur_scanner.dart';
import 'package:era_connect/src/verify/evm.dart';
import 'package:test/test.dart';

/// Cross-implementation parity: the fixture was generated by the reference implementation
/// SDK from deterministic synthetic material (the standard public BIP-39 test
/// seed). For identical inputs this port must produce byte-identical request
/// CBOR, parse the recorded replies to the same fields, and reach the same
/// verification verdicts — including on the tampered replies.
void main() {
  final fixture = jsonDecode(
    File('test/fixtures/parity/evm.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final era = EvmChain(EraConnectConfig(origin: fixture['origin'] as String));
  final requests =
      (fixture['requests'] as List<dynamic>).cast<Map<String, dynamic>>();
  final replies =
      (fixture['replies'] as List<dynamic>).cast<Map<String, dynamic>>();

  EvmSignRequestProps propsOf(Map<String, dynamic> props) {
    final addressHex = props['addressHex'] as String?;
    return EvmSignRequestProps(
      requestId: props['requestId'] as String,
      signData: hexToBytes(props['signDataHex'] as String),
      dataType: props['dataType'] as int,
      path: props['path'] as String,
      xfp: props['xfp'] as String,
      chainId: props['chainId'] as int?,
      address: addressHex == null ? null : hexToBytes(addressHex),
      origin: props['origin'] as String?,
    );
  }

  SignRequest<EvmSignatureResult> buildRequest(String name) {
    final found = requests.firstWhere(
      (r) => r['name'] == name,
      orElse: () => throw StateError('no request case $name'),
    );
    return era
        .generateSignRequest(propsOf(found['props'] as Map<String, dynamic>));
  }

  group('requests match the reference vectors byte for byte', () {
    for (final request in requests) {
      final name = request['name'] as String;
      final throws = request['throws'] as String?;
      test(name, () {
        if (throws != null) {
          expect(
            () => era.generateSignRequest(
                propsOf(request['props'] as Map<String, dynamic>)),
            throwsA(isA<EraSdkError>().having((e) => e.code, 'code', throws)),
          );
          return;
        }
        final built = era.generateSignRequest(
            propsOf(request['props'] as Map<String, dynamic>));
        expect(built.ur.type, request['urType']);
        expect(bytesToHex(built.ur.cbor), request['cborHex']);
      });
    }
  });

  group('replies parse and verify to the recorded verdicts', () {
    for (final reply in replies) {
      final name = reply['name'] as String;
      test(name, () {
        final scanner = buildRequest(reply['requestName'] as String).scanner();
        final feed = scanner.receivePart(reply['replyUr'] as String);
        expect(feed, isA<ScanComplete>());

        final expectation = reply['expect'] as String?;
        if (expectation != null) {
          expect(expectation, startsWith('throws:'));
          final code = expectation.substring('throws:'.length);
          expect(
            () => scanner.parse(),
            throwsA(isA<EraSdkError>().having((e) => e.code, 'code', code)),
          );
          return;
        }

        final parsed = scanner.parse();
        final expected = reply['parsed'] as Map<String, dynamic>;
        expect(bytesToHex(parsed.requestId), expected['requestIdHex']);
        expect(bytesToHex(parsed.signature), expected['signatureHex']);
        expect(bytesToHex(parsed.r), expected['rHex']);
        expect(bytesToHex(parsed.s), expected['sHex']);
        expect(parsed.v, BigInt.parse(expected['v'] as String));
        expect(parsed.recoveryId, expected['recoveryId']);

        final verify = reply['verify'] as Map<String, dynamic>;
        final result = verifyEvmSignature(VerifyEvmSignatureArgs(
          signData: hexToBytes(verify['signDataHex'] as String),
          dataType: verify['dataType'] as int,
          signature: parsed.signature,
          address: hexToBytes(verify['addressHex'] as String),
        ));
        final verdict = switch (verify['verdict'] as String) {
          'ok-checked' => result.ok && result.checked,
          'ok-unchecked' => result.ok && !result.checked,
          'verify:false' => !result.ok,
          final other => throw StateError('unknown verdict $other'),
        };
        expect(verdict, isTrue,
            reason: 'verdict ${verify['verdict']} for $name, '
                'got ok=${result.ok} checked=${result.checked} '
                'reason=${result.reason}');
      });
    }
  });

  test('the reused signData verifies against reEncodedSignData equality', () {
    // The re-encode guard: byte-equal payload passes, a divergent one fails.
    final valid = replies.firstWhere((r) => r['name'] == 'parity_v');
    final verify = valid['verify'] as Map<String, dynamic>;
    final signData = hexToBytes(verify['signDataHex'] as String);
    final signature = hexToBytes(
        (valid['parsed'] as Map<String, dynamic>)['signatureHex'] as String);
    final address = hexToBytes(verify['addressHex'] as String);

    final same = verifyEvmSignature(VerifyEvmSignatureArgs(
      signData: signData,
      dataType: EvmDataType.transaction,
      signature: signature,
      address: address,
      reEncodedSignData: signData,
    ));
    expect(same.ok, isTrue);
    expect(same.checked, isTrue);

    final drifted = Uint8List.fromList(signData);
    drifted[0] ^= 0x01;
    final diverged = verifyEvmSignature(VerifyEvmSignatureArgs(
      signData: signData,
      dataType: EvmDataType.transaction,
      signature: signature,
      address: address,
      reEncodedSignData: drifted,
    ));
    expect(diverged.ok, isFalse);
  });
}
