import 'dart:convert';
import 'dart:io';

import 'package:era_connect/src/chains/shared.dart';
import 'package:era_connect/src/chains/solana.dart';
import 'package:era_connect/src/core/bytes.dart';
import 'package:era_connect/src/core/errors.dart';
import 'package:era_connect/src/verify/solana.dart';
import 'package:test/test.dart';

/// Cross-implementation parity: the fixture was generated by the TypeScript
/// SDK from fixed inputs (synthetic sha256-of-a-constant key material only).
/// For the same inputs this port must emit byte-identical request CBOR and
/// parse/verify the recorded replies to the same verdicts.
void main() {
  final fixture = jsonDecode(
    File('test/fixtures/parity/solana.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  final era =
      SolanaChain(EraConnectConfig(origin: fixture['origin'] as String));
  final requestId = fixture['requestId'] as String;
  final signData = hexToBytes(fixture['signDataHex'] as String);
  final path = fixture['path'] as String;
  final xfp = fixture['xfp'] as String;
  final publicKey = hexToBytes(
      (fixture['key'] as Map<String, dynamic>)['publicKeyHex'] as String);

  group('solana requests match the TypeScript SDK byte for byte', () {
    for (final request
        in (fixture['requests'] as List).cast<Map<String, dynamic>>()) {
      test(request['name'] as String, () {
        final props = request['props'] as Map<String, dynamic>;
        final built = era.generateSignRequest(SolSignRequestProps(
          requestId: requestId,
          signData: signData,
          signType: props['signType'] as int?,
          path: path,
          xfp: xfp,
          publicKey: props['publicKeyHex'] == null
              ? null
              : hexToBytes(props['publicKeyHex'] as String),
          address: props['address'] as String?,
        ));
        expect(built.ur.type, request['urType']);
        expect(bytesToHex(built.ur.cbor), request['cborHex']);
        expect(built.ur.toString(), request['ur']);
      });
    }
  });

  group('solana replies parse and verify to the recorded verdicts', () {
    for (final reply
        in (fixture['replies'] as List).cast<Map<String, dynamic>>()) {
      test(reply['name'] as String, () {
        final parsed = era.parseSignature(
          reply['ur'] as String,
          ExpectedReply(requestId: requestId),
        );
        final recorded = reply['parsed'] as Map<String, dynamic>;
        expect(bytesToHex(parsed.requestId), recorded['requestIdHex']);
        expect(bytesToHex(parsed.signature), recorded['signatureHex']);

        expect(reply['verdict'], 'verify:true');
        final result = verifySolanaSignature(VerifySolanaSignatureArgs(
          signData: signData,
          signature: parsed.signature,
          publicKey: publicKey,
        ));
        expect(result.ok, isTrue);
        expect(result.checked, isTrue);
      });
    }
  });

  group('tampered solana replies fail the way the fixture records', () {
    for (final tampered
        in (fixture['tampered'] as List).cast<Map<String, dynamic>>()) {
      test(tampered['name'] as String, () {
        final expected = tampered['expect'] as String;
        if (expected.startsWith('throws:')) {
          final code = expected.substring('throws:'.length);
          expect(
            () => era.parseSignature(
              tampered['ur'] as String,
              ExpectedReply(requestId: requestId),
            ),
            throwsA(isA<EraSdkError>().having((e) => e.code, 'code', code)),
          );
          return;
        }
        expect(expected, 'verify:false');
        final parsed = era.parseSignature(
          tampered['ur'] as String,
          ExpectedReply(requestId: requestId),
        );
        final recorded = tampered['parsed'] as Map<String, dynamic>;
        expect(bytesToHex(parsed.signature), recorded['signatureHex']);
        final result = verifySolanaSignature(VerifySolanaSignatureArgs(
          signData: signData,
          signature: parsed.signature,
          publicKey: publicKey,
        ));
        expect(result.ok, isFalse);
      });
    }
  });
}
