import 'dart:convert';
import 'dart:io';

import 'package:era_connect/src/chains/shared.dart';
import 'package:era_connect/src/chains/sui.dart';
import 'package:era_connect/src/core/bytes.dart';
import 'package:era_connect/src/core/errors.dart';
import 'package:era_connect/src/verify/sui.dart';
import 'package:test/test.dart';

/// Parity against the TypeScript SDK: fixtures in
/// `test/fixtures/parity/sui.json` are generated by the reference
/// implementation from fixed synthetic inputs; the Dart port must produce the
/// identical request bytes and read the identical replies.
void main() {
  final fixture = jsonDecode(
    File('test/fixtures/parity/sui.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final requests = (fixture['requests'] as List).cast<Map<String, dynamic>>();
  final replies = (fixture['replies'] as List).cast<Map<String, dynamic>>();

  SignRequest<SuiSignatureResult> rebuild(Map<String, dynamic> entry) {
    final props = entry['props'] as Map<String, dynamic>;
    final chain = SuiChain();
    switch (entry['name'] as String) {
      case 'signRequest':
        return chain.generateSignRequest(SuiSignRequestProps(
          requestId: props['requestId'] as String,
          intentMessage: hexToBytes(props['intentMessageHex'] as String),
          path: props['path'] as String,
          xfp: props['xfp'] as String,
          address: props['addressHex'] as String,
        ));
      case 'signHashRequest':
        return chain.generateSignHashRequest(SuiSignHashRequestProps(
          requestId: props['requestId'] as String,
          messageHash: hexToBytes(props['messageHashHex'] as String),
          path: props['path'] as String,
          xfp: props['xfpNumber'] as int,
          origin: props['origin'] as String,
        ));
      default:
        throw StateError('unknown fixture request ${entry['name']}');
    }
  }

  group('Sui parity: requests', () {
    for (final entry in requests) {
      test('${entry['name']} rebuilds byte-identical', () {
        final request = rebuild(entry);
        expect(request.ur.type, entry['urType']);
        expect(bytesToHex(request.ur.cbor), entry['cborHex']);
      });
    }
  });

  group('Sui parity: replies', () {
    final byName = {for (final r in requests) r['name'] as String: r};

    SuiSignatureResult parseVia(Map<String, dynamic> reply) {
      final request = rebuild(byName[reply['requestName'] as String]!);
      final scanner = request.scanner();
      scanner.receivePart(reply['ur'] as String);
      return scanner.parse();
    }

    VerifyResultExpectation runVerify(Map<String, dynamic> reply) {
      final parsed = reply['parsed'] as Map<String, dynamic>;
      final args = reply['verify'] as Map<String, dynamic>;
      final intentHex = args['intentMessageHex'] as String?;
      final hashHex = args['messageHashHex'] as String?;
      final result = verifySuiSignature(VerifySuiSignatureArgs(
        intentMessage: intentHex == null ? null : hexToBytes(intentHex),
        messageHash: hashHex == null ? null : hexToBytes(hashHex),
        signature: hexToBytes(parsed['signatureHex'] as String),
        publicKey: hexToBytes(parsed['publicKeyHex'] as String),
        expectedPublicKey: hexToBytes(args['expectedPublicKeyHex'] as String),
      ));
      return VerifyResultExpectation(result.ok, result.checked);
    }

    for (final reply in replies) {
      final expected = reply['expect'] as String;
      test('${reply['name']} -> $expected', () {
        if (expected.startsWith('throws:')) {
          final code = expected.substring('throws:'.length);
          final request = rebuild(byName[reply['requestName'] as String]!);
          final scanner = request.scanner();
          scanner.receivePart(reply['ur'] as String);
          expect(
            scanner.parse,
            throwsA(isA<EraSdkError>().having((e) => e.code, 'code', code)),
          );
          return;
        }

        final parsedExpectation = reply['parsed'] as Map<String, dynamic>;
        final parsed = parseVia(reply);
        expect(bytesToHex(parsed.requestId), parsedExpectation['requestIdHex']);
        expect(bytesToHex(parsed.signature), parsedExpectation['signatureHex']);
        expect(bytesToHex(parsed.publicKey), parsedExpectation['publicKeyHex']);

        final verdict = runVerify(reply);
        switch (expected) {
          case 'verify:true':
            expect(verdict.ok, isTrue);
            expect(verdict.checked, isTrue);
          case 'verify:false':
            expect(verdict.ok, isFalse);
          default:
            throw StateError('unknown expectation $expected');
        }
      });
    }

    test('standalone parseSignature validates the echo too', () {
      final reply = replies.firstWhere((r) => r['name'] == 'hashReply');
      final chain = SuiChain();
      final parsed = chain.parseSignature(
        reply['ur'] as String,
        const ExpectedReply(requestId: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
      );
      final parsedExpectation = reply['parsed'] as Map<String, dynamic>;
      expect(bytesToHex(parsed.signature), parsedExpectation['signatureHex']);

      final tampered =
          replies.firstWhere((r) => r['name'] == 'wrongRequestIdEcho');
      expect(
        () => chain.parseSignature(
          tampered['ur'] as String,
          const ExpectedReply(
              requestId: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
        ),
        throwsA(isA<EraSdkError>()
            .having((e) => e.code, 'code', 'request-id-mismatch')),
      );
    });
  });
}

/// The slice of a verify result the fixture pins (`ok` + `checked`).
class VerifyResultExpectation {
  const VerifyResultExpectation(this.ok, this.checked);

  final bool ok;
  final bool checked;
}
