import 'dart:convert';
import 'dart:io';

import 'package:era_connect/src/chains/shared.dart';
import 'package:era_connect/src/chains/xrp.dart';
import 'package:era_connect/src/core/bytes.dart';
import 'package:era_connect/src/core/errors.dart';
import 'package:era_connect/src/scan/ur_scanner.dart';
import 'package:era_connect/src/verify/xrp.dart';
import 'package:test/test.dart';

/// Parity against the TypeScript SDK: fixtures in
/// `test/fixtures/parity/xrp.json` are generated by the reference
/// implementation from fixed synthetic inputs; the Dart port must produce the
/// identical request bytes and read the identical replies.
///
/// XRP is the untyped-`ur:bytes` chain: no request id in either direction, so
/// the fixture leans on `verifyXrpSignature` (the walker + SHA-512-half
/// signing hash) as the binding, tampered variants included.
void main() {
  final fixture = jsonDecode(
    File('test/fixtures/parity/xrp.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final requests = (fixture['requests'] as List).cast<Map<String, dynamic>>();
  final replies = (fixture['replies'] as List).cast<Map<String, dynamic>>();

  SignRequest<XrpSignatureResult> rebuild(Map<String, dynamic> entry) {
    final props = entry['props'] as Map<String, dynamic>;
    final chain = XrpChain();
    switch (entry['name'] as String) {
      case 'signRequestObject':
        return chain.generateSignRequest(
          XrpSignRequestProps(
            transaction: props['transaction'] as Map<String, dynamic>,
          ),
        );
      case 'signRequestString':
        return chain.generateSignRequest(
          XrpSignRequestProps(
            transaction: props['transactionJson'] as String,
          ),
        );
      default:
        throw StateError('unknown fixture request ${entry['name']}');
    }
  }

  group('XRP parity: requests', () {
    for (final entry in requests) {
      test('${entry['name']} rebuilds byte-identical', () {
        final request = rebuild(entry);
        expect(request.ur.type, entry['urType']);
        expect(bytesToHex(request.ur.cbor), entry['cborHex']);
        expect(entry['requestIdAbsent'], isTrue);
        expect(request.requestId, isNull);
      });
    }
  });

  group('XRP parity: replies', () {
    final byName = {for (final r in requests) r['name'] as String: r};

    XrpSignatureResult parseVia(Map<String, dynamic> reply) {
      final request = rebuild(byName[reply['requestName'] as String]!);
      final scanner = request.scanner();
      scanner.receivePart(reply['ur'] as String);
      return scanner.parse();
    }

    for (final reply in replies) {
      final expected = reply['expect'] as String;
      test('${reply['name']} -> $expected', () {
        if (expected.startsWith('throws:')) {
          final code = expected.substring('throws:'.length);
          final chain = XrpChain();
          expect(
            () => chain.parseSignature(reply['ur'] as String),
            throwsA(isA<EraSdkError>().having((e) => e.code, 'code', code)),
          );
          if (code == 'wrong-ur-type') {
            // The request scanner refuses the frame before assembly, too.
            final request = rebuild(byName[reply['requestName'] as String]!);
            final scanner = request.scanner();
            final fed = scanner.receivePart(reply['ur'] as String);
            expect(fed, isA<ScanRejected>());
            expect((fed as ScanRejected).rejection.code, code);
          }
          return;
        }

        final parsedExpectation = reply['parsed'] as Map<String, dynamic>;
        final parsed = parseVia(reply);
        expect(bytesToHex(parsed.signedTx), parsedExpectation['signedTxHex']);

        // Standalone parse reads the same bytes.
        final standalone = XrpChain().parseSignature(reply['ur'] as String);
        expect(
            bytesToHex(standalone.signedTx), parsedExpectation['signedTxHex']);

        final args = reply['verify'] as Map<String, dynamic>;
        final verdict = verifyXrpSignature(
          VerifyXrpSignatureArgs(
            signedTx: parsed.signedTx,
            expectedSigningPubKey: args['expectedSigningPubKey'] as String,
          ),
        );
        switch (expected) {
          case 'verify:true':
            expect(verdict.ok, isTrue);
            expect(verdict.checked, isTrue);
          case 'verify:false':
            expect(verdict.ok, isFalse);
          case 'verify:unverifiable':
            expect(verdict.ok, isTrue);
            expect(verdict.checked, isFalse);
          default:
            throw StateError('unknown expectation $expected');
        }
      });
    }
  });
}
